name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "config/**"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      # 明确指定要编译的板子和 Shield
      board: nice_nano_v2
      shield: cocot46p
